TimeManageSystem/Models/Engineer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace TimeManageSystem.Models
{
    public class Engineer
    {
        [Key]
        public int EnegerId { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = " DataTask")]
        public DateTime DataTaskStart { get; set; } //дата

        [DataType(DataType.Date)]
        [Display(Name = " DataTaskFinish")]
        public DateTime DataTaskFinish { get; set; } //дата

        public string Descriptionofwork { get; set; }//описание работы
        public string Kindofactiviti { get; set; } //вид деятельности

        [DataType(DataType.Time)]
        [Display(Name = " Worktime")]
        public DateTime Worktime { get; set; }//Время работы

        public string NameProject { get; set; }
    }
}

TimeManageSystem/Controllers/EngineerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeManageSystem.Models;
using Microsoft.EntityFrameworkCore;

namespace TimeManageSystem.Controllers
{
    public class EngineerController : Controller
    {
        private TimeContext db;
        public EngineerController(TimeContext context)
        {
            db = context;
        }
        public async Task<IActionResult> Indexe()
        {
             return View(await db.Engineers.ToListAsync());
        }
        public IActionResult Createe()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Createe(Engineer engineer)
        {
            db.Engineers.Add(engineer);
            await db.SaveChangesAsync();
            return RedirectToAction("Indexe");
        }

    }
}

TimeManageSystem/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TimeManageSystem.Models;
using Microsoft.EntityFrameworkCore;

namespace TimeManageSystem.Controllers
{
    public class ProjectController : Controller
    {
        private TimeContext db;
        public ProjectController(TimeContext context)
        {
            db = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await db.Projects.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Project project = await db.Projects.FirstOrDefaultAsync(p => p.Id == id);
                if (project != null)
                    return View(project);
            }
            return NotFound();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Project project)
        {
            db.Projects.Add(project);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Project project = await db.Projects.FirstOrDefaultAsync(p => p.Id == id);
                if (project != null)
                    return View(project);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Project project)
        {
            db.Projects.Update(project);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Project project = await db.Projects.FirstOrDefaultAsync(p => p.Id == id);
                if (project != null)
                    return View(project);
            }
            return NotFound();
        }

        //[HttpPost]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id != null)
        //    {
        //        Project project = await db.Projects.FirstOrDefaultAsync(p => p.Id == id);
        //        if (project != null)
        //        {
        //            db.Projects.Remove(project);
        //            await db.SaveChangesAsync();
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    return NotFound();
        //}
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Project project = new Project { Id = id.Value };
                db.Entry(project).State = EntityState.Deleted;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

TimeManageSystem/Views/Engineer/CreateE.cshtml
@model TimeManageSystem.Models.Engineer
@{
        ViewBag.Title = "Заполнение данных";
      
    }
<form asp-action="createe" asp-controller="engineer">

    @*<div class="col-md-10">
            @Html.DropDownList("EnegerId", (IEnumerable<SelectListItem>)ViewBag.Progects)
        </div>*@
    <div>
            <label asp-for="NameProject">Вид деятельности</label><br />
            <select size="1" required name="NameProject" asp-for="NameProject">
                <option selected>Выберите проект</option>
                <option value="БД">БД</option>
                <option value="Time manegment system">Time manegment system</option>
                <option value="Создание проекта за два дня">Создание проекта за два дня</option>
                <option value="game boi system">game boi system</option>
                <option value="peaceduke">peaceduke</option>
            </select>
            <span asp-validation-for="NameProject" />
        </div><br />
    <div class="form-group">
        <label asp-for="DataTaskStart" class="control-label">Дата нач.проекта</label>
        <input type="datetime-local" asp-for="DataTaskStart" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="DataTaskFinish" class="control-label">Дата окон.проекта</label>
        <input type="datetime-local" asp-for="DataTaskFinish" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Descriptionofwork" class="control-label">Описание выполненой работы</label>
        <input type="text" asp-for="Descriptionofwork" class="form-control" />
    </div>
    @*<div>
            <label asp-for="Kindofactiviti">Вид деятельности</label><br />
            <select size="1" required name="Kindofactiviti" asp-for="Kindofactiviti">
                <option selected>Выберите действие</option>
                <option value="В разработке">В разработке</option>
                <option value="В доработке">В доработке</option>
                <option value="Выполнено">Выполнено</option>
            </select>
            <span asp-validation-for="Kindofactiviti" />
        </div>*@<br />
    @*<div class="form-group">
            <label asp-for="Kindofactiviti" class="control-label">Вид деятельности</label>
            <input type="text" asp-for="Kindofactiviti" class="form-control" />
        </div>*@
    <div class="form-group">
        <label asp-for="Worktime" class="control-label">Время работы</label>
        <input type="time" asp-for="Worktime" class="form-control" />
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

TimeManageSystem/Views/Engineer/IndexE.cshtml
<form asp-controller="Project" method="post">
    <input class="btn btn-success btn-lg btn-block" asp-controller="Project" type="submit" value="Просмотр проектов" asp-action="Index" />
</form>


@model IEnumerable<TimeManageSystem.Models.Engineer>
@{
    ViewBag.Title = "Все проекты ";
}
<a asp-action="Createe">Заполнитьь форму для выполнения заданий</a>
<table class="table">
    <tr><td>Название проекта</td><td>Дата нач.проекта</td><td>Дата окон.проекта</td><td>Описание выполненой работы</td><td>Время работы</td></tr>
    @foreach (var item in Model)
    {
        <tr><td>@item.NameProject</td><td>@item.DataTaskStart</td><td>@item.DataTaskFinish</td><td>@item.Descriptionofwork</td><td>@item.Worktime</td></tr>
    }
</table>