TimeManageSystem/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace TimeManageSystem.Models
{
    public class User : IdentityUser
    {
        public string Name { get; set; }
        public string Position { get; set; }
        public string Surname { get; set; }
    }
}

TimeManageSystem/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using TimeManageSystem.Models;
using TimeManageSystem.ViewModels;

namespace TimeManageSystem.Controllers
{
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Surname = model.Surname, Name = model.Name, Position = model.Position };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;


                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

TimeManageSystem/Views/Users/Create.cshtml
@model TimeManageSystem.ViewModels.CreateUserViewModel
@{
    ViewBag.Title = "Добавление пользователя";
}
<form asp-action="Create" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Пароль</label>
        <input type="text" asp-for="Password" class="form-control" />
    </div>
    <div>
        <label asp-for="Surname" class="control-label">Surname</label>
        <input type="text" asp-for="Surname" class="form-control" />

    </div>
    <div>
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />

    </div>
    <div>
        <label asp-for="Position"></label><br />
        <select size="1" required name="Position" asp-for="Position">
            <option selected>Выберите должность</option>
            <option value="Engineer">Инженер</option>
            <option value="Team_lead">Руководитель</option>
            <option value="Project_manager">Менеджер</option>
        </select>
        <span asp-validation-for="Position" />
    </div><br/>
    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-default" />
    </div>
</form>

TimeManageSystem/Views/Users/Edit.cshtml
@model TimeManageSystem.ViewModels.EditUserViewModel
@{
    ViewBag.Title = "Редактирование пользователя";
}
<form asp-action="Edit" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
    </div><br/>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

TimeManageSystem/Views/Users/Index.cshtml
@model IEnumerable<TimeManageSystem.Models.User>
@{
    ViewBag.Title = "Список пользователей";
}



<table class="table">
    <tr><th>Email</th><th></th></tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>

            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@user.Id">Изменить</a>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Удалить
                    </button>
                </form>
            </td>
        </tr>
    }
</table><br/>
        
<a asp-action="Create">Добавить пользователя</a>
          